spring:
  datasource:
    url: jdbc:mysql://localhost:3306/device-api?createDatabaseIfNotExist=true
    username: root
    password: rootpass
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    properties:
     hibernate:
      dialect: org.hibernate.dialect.MariaDBDialect
    hibernate:
      ddl-auto: none
    database-platform: org.hibernate.dialect.MariaDBDialect
  data:
    redis:
      host: ${SPRING_REDIS_HOST:localhost}
      port: ${SPRING_REDIS_PORT:6379}
  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:db/migration

management:
  endpoints:
    web:
      exposure:
        include: "*"
  metrics:
    export:
      prometheus:
        enabled: true

server:
  port: 8080
